config/routes.rb
Rails.application.routes.draw do
  resources       :vehicles   do
    resources     :shift_vehicles
    end
  resources       :shifts
  resources       :user_shifts
  resources       :rides
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_scope    :user do get '/users/sign_out' => 'devise/sessions#destroy' end
  devise_for      :users
  # resources       :sessions, only: [:new, :create, :destroy]
  post            'create_shift_vehicles' => "shifts#create_vs"
  root            'static_pages#home'
  post            'create_shift' => 'shifts#create'
  get             'work' => 'shifts#index'
  get             'about' => 'static_pages#about'
  get             'policies' => 'static_pages#policies'
  get             'faq' => 'static_pages#faq'
end

app/models/shift.rb
class Shift < ActiveRecord::Base
  has_many :user_shifts, dependent: :destroy
  has_many :vehicles, through: :shift_vehicles
  has_many :shift_vehicles, dependent: :destroy
  accepts_nested_attributes_for :user_shifts
  accepts_nested_attributes_for :shift_vehicles

  # validates_time :created_at, :on_or_before => '2:30_am'
  scope :active, -> { where(:created_at => Time.now.ago(5.hours)..Time.now)}
  validates        :created_at, uniqueness: true
  validate         :active_shift_limit

  def to_s
    name
  end

private
  # def hours_of_operation
  # end

  def active_shift_limit
    if Shift.active.count >= 1
    errors.add(:base, "Shift already exists for tonight")
    end
  end

  # def create_vehicles_shifts(vehicle)
  #   s = Shift.active.first
  #   s.vehicles_shifts.build
  #   s.vehicles_shifts.create(vehicle_id: vehicle)
  # end
  #
  # def assign_pid(pid)
  #   s = Shift.active.first
  #   s.users_shifts.build
  #   s.users_shifts.first_or_create!(user_id: current_user.id)
  #   update_attributes(position_id: pid)
  # end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => :create
  before_filter :authenticate_user!

  def index
    s = Shift.active.first
    @vehicles = Vehicle.all
    @shift = s
    @shift_vehicles = s.shift_vehicles.build
    @sv = s.shift_vehicles.all
    s.user_shifts.build
    @user_shift = s.user_shifts.first
    #this could be a problem when other users start getting into the system
  end

  def show
    @shift = Shift.find(params[:id])
  end

  def new
    @shift = Shift.active.first
    @shift.shift_vehicles.build
  end

  def edit
  end

#if an active shift does not exist create
#an active shift, otherwise redirect to the
#current active shift
  def create
    Shift.active.first_or_create!
    s = Shift.active.first
    s.user_shifts.build
    s.user_shifts.find_or_create_by!(user_id: current_user.id)
    redirect_to work_path
  end

  def create_vs
    params[:shift][:shift_vehicle][:vehicle_id].each do |vehicle| unless vehicle == ""
      s = Shift.active.first
      vehicle_shift = s.shift_vehicles.create(vehicle_id: vehicle)
    end
  end
    redirect_to work_path
  end

  def update
    # s = Shift.active.first
    # params[:shift_vehicles].each do |shift_vehicle|
    #   if shift_vehicle[:vehicle_id] != ""
    #     s.vehicles_shifts.create(shift_vehicle_params(shift_vehicle))
    #   end
    # end
    # s.shift_vehicles.find(params[:vehicle_id])
    # s.map {|veh| veh.vehicles_shifts.create}
    # s.find(params[:id])
    # s.vehicles_shifts.create
    # redirect_to work_path
  end

  def destroy
  end

  private
  def shift_params
    params.require(:shift).permit(:vehicle_id, user_shifts_attributes: [:id, :position_id, :shift_id, :user_id, :shift_vehicle_id, :created_at, :updated_at],
                                               shift_vehicles_attributes: [:id, :start_mileage, :end_mileage, :start_gas, :end_gas, :shift_id, :vehicle_id, :created_at, :updated_at],
                                               vehicles_attributes: [:id, :vehicle_number, :created_at, :updated_at])
  end

  # def vehicles_shifts_create(vn)
  #   s = Shift.active.first
  #   s.vehicles_shifts.build
  #   s.vehicles_shifts.create!(vehicle_id: vn)
  # end
end
  # @vehicles_shifts = @shift.create_vehicles_shift(vehicle_id: vn)

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/shifts/_form.html.erb
<h3>Create Shift Vehicles</h3>
  <%= simple_form_for @shift, url: create_shift_vehicles_path, method: :post do |f| %>
    <%= f.simple_fields_for @shift_vehicles do |ff| %>
      <%= ff.input :vehicle_id, collection: Vehicle.all, as: :check_boxes, label_method: "model" %>
    <% end %>
    <div>
    <%= f.button :submit, 'Choose Vehicles!' %>
  </div>
  <% end %>

app/views/shifts/_form2.html.erb
<h3>Create Shift Vehicles</h3>
<% @vehicles.each do |vehicle| %>
<%= simple_form_for(@shift) do |f| %>
<table class="table table-hover">
  <thead>
    <th>    </th>
    <th> ID </th>
    <th>Vehicle Number</th>
    <th>Model</th>
    <th>Created At</th>
    <th>Updated At</th>
    <th></th>
  </thead>
  <tbody>
      <tr>
        <td><%= f.simple_fields_for :shift_vehicles do |ff| %>
        <%= ff.input :vehicle_id, as: :boolean %></td>
            <% end %>
        <td><%= vehicle.id %></td>
        <td><%= vehicle.vehicle_number %></td>
        <td><%= vehicle.model %></td>
        <td><%= vehicle.created_at %></td>
        <td><%= vehicle.updated_at %></td>
        </tr>
      <%= f.button :submit %>
        <% end %>
    <% end %>
  </tbody>
</table>

app/views/shifts/_position_id.html.erb
<div class="btn-group btn-group-justified" role="group" aria-label="...">
  <div class="btn-group" role="group">
    <%= form_for(@user_shift, remote: true) do |f| %>
      <%= f.hidden_field :position_id, value: 1 %>
      <%= f.submit 'Dispatcher', class: "btn btn-default" %>
    <% end %>
  </div>
  <div class="btn-group" role="group">
    <%= form_for(@user_shift, remote: true) do |f| %>
      <%= f.hidden_field :position_id, value: 2 %>
      <%= f.submit 'Navigator', class: "btn btn-default" %>
    <% end %>
  </div>
  <div class="btn-group" role="group">
    <%= form_for(@user_shift, remote: true) do |f| %>
      <%= f.hidden_field :position_id, value: 3 %>
      <%= f.submit 'Driver', class: "btn btn-default" %>
    <% end %>
  </div>
</div>

app/views/shifts/_shift_vehicle.html.erb
<%= simple_form_for @user_shift, html: {class: "form-inline"}, remote: true do |f| %>
  <%= f.association :shift_vehicle, label_method: "vehicle_id" %>
  <%= f.button :submit %>
<% end %>

app/views/shifts/_vehicles.html.erb
  <h3>Vehicles Shifts</h3>
  <table class="table table-hover">
    <thead>
      <th>Vehicles Shift ID</th>
      <th>Start Mileage</th>
      <th>End Mileage</th>
      <th>Start Gas</th>
      <th>End Gas</th>
      <th>Shift ID</th>
      <th>Vehicle ID</th>
      <th>Created At</th>
      <th>Updated At</th>
    </thead>
    <tbody>
      <%= @vehicles_shift.each do |vehicles_shift| %>
        <tr>
          <td><%= vehicles_shift.id %></td>
          <td><%= vehicles_shift.start_mileage %></td>
          <td><%= vehicles_shift.end_mileage %></td>
          <td><%= vehicles_shift.start_gas %></td>
          <td><%= vehicles_shift.end_gas %></td>
          <td><%= vehicles_shift.shift_id %></td>
          <td><%= vehicles_shift.vehicle_id %></td>
          <td><%= vehicles_shift.created_at %></td>
          <td><%= vehicles_shift.updated_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <h3>Create Vehicles Shifts</h3>
  <table class="table table-hover">
    <thead>
      <th> ID </th>
      <th>Vehicle Number</th>
      <th>Model</th>
      <th>Created At</th>
      <th>Updated At</th>
      <th></th>
    </thead>
    <tbody>
      <% @vehicles.each do |vehicle| %>
        <tr>
          <%= form_for vehicle do |f| %>
          <td><%= check_box_tag 'vehicle_ids[]', vehicle.id %></td>
          <td><%= vehicle.vehicle_number %></td>
          <td><%= vehicle.model %></td>
          <td><%= vehicle.created_at %></td>
          <td><%= vehicle.updated_at %></td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <div class="btn-group" role="group" aria-label="...">
    <div class="btn-group" role="group">
      <%= submit_tag "Create Vehicles Shifts" %>

app/views/shifts/edit.html.erb
<h1>Editing Shift</h1>

<%= render 'form' %>

<%= link_to 'Show', @shift %> |
<%= link_to 'Back', shifts_path %>

app/views/shifts/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
</head>
<body>
  <div id="skillSet">
<%= render partial: "position_id" %>
</div>
<div id="skillSSet" class="skillSSet">
<%= render partial: "shift_vehicle" %>
</div>
<style type="text/css">
#skillSSet {
	display: none;
}
</style>
<#style type="text/css">
     #html { height: 100% }
     #body { height: 100%; margin: 0; padding: 0 }
     #map-canvas { height: 400px }
 <#/style>
 <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCaCZ1QamN4k1sIcjzkIPFmNWxOQKn5UCg&sensor=false"></script>
 <script>
   function set_map(state, city){
     var mapOptions = {
       center: new google.maps.LatLng(25.687944,-100.309403),
       zoom: 8,
       mapTypeId: google.maps.MapTypeId.ROADMAP
     };
     var map = new google.maps.Map(document.getElementById("map-canvas"),
     mapOptions);

     if(state == ""){
       address = city;
     }else{
       address = state + ',' + city;
     }

     var geocoder = new google.maps.Geocoder();

     geocoder.geocode({
       'address':address
     },

     function(result, status){
       if (status == google.maps.GeocoderStatus.OK){
         map.setCenter(result[0].geometry.location);

         var marker = new google.maps.Marker({
           map: map,
           position: result[0].geometry.location
         });
       }else{
         alert("Geocode was not successful for the following reason: " + status);
       }
     });
     return false;
   }

   $(document).ready(function(){
     set_map('Oregon', 'Eugene');
   })
 </script>
 <br></br>
 <div class="row">
   <div class="col-md-8">
 <div class="container-centered">
<div id="map-canvas"></div></div></div>
<div class="col-md-4">
<div class="panel panel-default">
<div class="panel-heading"><h2>Work</h2></div>
<div class="panel-body">
<ul class="list-group">
 <!--   <div style='width: 800px;'>
    <div id="map" style='width: 800px; height: 400px;'></div>
  </div> -->
    <li class="list-group-item"><p><strong>Shift ID</strong> <%= @shift.id %></p>
    <li class="list-group-item"><p><strong>Created At</strong> <%= @shift.created_at %></p>
    <li class="list-group-item"><p><strong>Updated At</strong> <%= @shift.updated_at %></p>
</ul>

</div>
</div>
</div>
</div>
  <h3>Users Shift</h3>
    <p><strong>Users Shift ID</strong> <%= @user_shift.id %></p>
    <p><strong>Position ID</strong> <%= @user_shift.position_id %></p>
    <p><strong>Shift ID</strong> <%= @user_shift.shift_id %></p>
    <p><strong>User ID</strong> <%= @user_shift.user_id %></p>
    <p><strong>Shift Vehicle ID</strong> <%= @user_shift.shift_vehicle_id %></p>
    <p><strong>Created At</strong> <%= @user_shift.created_at %></p>
    <p><strong>Updated At</strong> <%= @user_shift.updated_at %></p>

  <h3>Choose your Vehicle</h3>

  <h3>Shift Vehicles</h3>
  <table class="table table-hover">
    <thead>
      <th>ID</th>
      <th>Start Mileage</th>
      <th>End Mileage</th>
      <th>Start Gas</th>
      <th>End Gas</th>
      <th>Shift ID</th>
      <th>Vehicle ID</th>
      <th>Created At</th>
      <th>Updated At</th>
    </thead>
    <% @sv.each do |shift_vehicles| %>
    <tbody>
        <tr>
          <td><%= shift_vehicles.id %></td>
          <td><%= shift_vehicles.start_mileage %></td>
          <td><%= shift_vehicles.end_mileage %></td>
          <td><%= shift_vehicles.start_gas %></td>
          <td><%= shift_vehicles.end_gas %></td>
          <td><%= shift_vehicles.shift_id %></td>
          <td><%= shift_vehicles.vehicle_id %></td>
          <td><%= shift_vehicles.created_at %></td>
          <td><%= shift_vehicles.updated_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <script>$(document).ready(function() {
     $("#skillSet").find('.btn-group').bind('click', function() {
       $('.btn-group').remove();
       $("#skillSSet").fadeIn('fast');
  });
  });</script>
  <%= render 'form' %>
</body>
</html>

app/views/shifts/new.html.erb
<h1>New Shift</h1>

<%= render 'form' %>

<%= link_to 'Back', shifts_path %>

app/views/shifts/show.html.erb
<h1>Work</h1>
<p><strong>Vehicle ID</strong> <%= @shift.vehicle_id %></p>
<p><strong>Created At</strong> <%= @shift.created_at %></p>
<p><strong>Updated At</strong> <%= @shift.updated_at %></p>