config/routes.rb
Rails.application.routes.draw do
  resources       :vehicles   do
    resources     :shift_vehicles
    end
  resources       :shifts
  resources       :user_shifts
  resources       :rides
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_scope    :user do get '/users/sign_out' => 'devise/sessions#destroy' end
  devise_for      :users
  # resources       :sessions, only: [:new, :create, :destroy]
  post            'create_shift_vehicles' => "shifts#create_vs"
  root            'static_pages#home'
  post            'create_shift' => 'shifts#create'
  get             'work' => 'shifts#index'
  get             'about' => 'static_pages#about'
  get             'policies' => 'static_pages#policies'
  get             'faq' => 'static_pages#faq'
end

app/models/users_shift.rb
class UsersShift < ActiveRecord::Base
  belongs_to :shift
  belongs_to :user

  scope :active, -> { where(:created_at => Time.now.ago(5.hours)..Time.now)}

  def to_s
    name
  end
end

app/controllers/users_shifts_controller.rb
class UsersShiftsController < ApplicationController
  def index
  end

  def show
  end

  def new
    @users_shift = Users_shift.new
  end

  def edit
  end

  #if an active users_shift does not exist create one
  #a users shift has a unique user_id
  #user_id = current_user.id

  def create
  end

#update the position_id attribute and redirect to the work controller.
  def update
    @users_shift=UsersShift.find(params[:id])
    @users_shift.update(users_shift_params)
    @users_shift.save
    redirect_to work_path
  end

  def destroy
  end

private
  def users_shift_params
    params[:users_shift].permit(:position_id, :shift_id, :user_id, :created_at, :updated_at)
  end
end

app/helpers/users_shifts_helper.rb
module UsersShiftsHelper
end

app/views/users_shifts/_form.html.erb
<%= form_for(@users_shift) do |f| %>
  <% if @users_shift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@users_shift.errors.count, "error") %> prohibited this users_shift from being saved:</h2>

      <ul>
      <% @users_shift.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users_shifts/edit.html.erb
<h1>Editing Users Shift</h1>

<%= render 'form' %>

<%= link_to 'Show', @users_shift %> |
<%= link_to 'Back', users_shifts_path %>

app/views/users_shifts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users Shifts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users_shifts.each do |users_shift| %>
      <tr>
        <td><%= link_to 'Show', users_shift %></td>
        <td><%= link_to 'Edit', edit_users_shift_path(users_shift) %></td>
        <td><%= link_to 'Destroy', users_shift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Users shift', new_users_shift_path %>

app/views/users_shifts/new.html.erb
<h1>New Users Shift</h1>

<%= render 'form' %>

<%= link_to 'Back', users_shifts_path %>

app/views/users_shifts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_users_shift_path(@users_shift) %> |
<%= link_to 'Back', users_shifts_path %>