config/routes.rb
Rails.application.routes.draw do
  resources       :vehicles   do
    resources     :shift_vehicles
    end
  resources       :shifts
  resources       :user_shifts
  resources       :rides
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_scope    :user do get '/users/sign_out' => 'devise/sessions#destroy' end
  devise_for      :users
  # resources       :sessions, only: [:new, :create, :destroy]
  post            'create_shift_vehicles' => "shifts#create_vs"
  root            'static_pages#home'
  post            'create_shift' => 'shifts#create'
  get             'work' => 'shifts#index'
  get             'about' => 'static_pages#about'
  get             'policies' => 'static_pages#policies'
  get             'faq' => 'static_pages#faq'
end

app/models/ride.rb
class Ride < ActiveRecord::Base
  belongs_to :shift_vehicle

  accepts_nested_attributes_for :shift_vehicle
end

app/controllers/rides_controller.rb
require 'twilio-ruby'

class RidesController < ApplicationController
  before_filter :authenticate_user!, only: [:index, :edit, :destroy, :show, :update]
  require 'twilio-ruby'

  def index
    @rides=Ride.all
  end

  def new
    @ride=Ride.new
  end

  def create
    @ride=Ride.new
    @ride.update(ride_params)
    @ride.save
    redirect_to rides_path
  end

  def edit
    @ride=Ride.find(params[:id])
  end

  def show
    @ride=Ride.find(params[:id])
  end

  def update
    @ride=Ride.find(params[:id])
    @ride.update(ride_params)
    @ride.save
    redirect_to rides_path
  end

  def destroy
    @ride=Ride.find(params[:id])
    @ride.delete
    redirect_to rides_path
  end

  # def call
  #   account_sid = 'ACfb98cd2cee4e1776236b872f4dbb0cb3'
  #   auth_token = '3e95a4d9cdf4d364974b16907c5da6c7'
  #   @client = Twilio::REST::Client.new account_sid, auth_token
  #   @client.account.calls.create({
  #     :to => '+15035777844',
  #   	:from => '+15038820432',
  #   	:method => 'GET',
  #   	:fallback_method => 'GET',
  #   	:status_callback_method => 'GET',
  #   	:record => 'false'
  #   })
  #   redirect_to rides_path
  # end

  private
  # def assign_van
  # end
  # helper_method :assign_vehicle

  def ride_params
    params[:ride].permit(:vehicle_id, :name, :sid, :phone, :passengers, :origin, :destination, :shift_vehicle_id)
  end

end

app/helpers/rides_helper.rb
module RidesHelper
end

app/views/rides/_form.html.erb
<%= form_for @ride do |form| %>
  <div class="form-group">
  <label>Student ID</label>
  <%= form.text_field :sid, class: "form-control" %>
  </div>
  <div class="form-group">
  <label>Name</label>
  <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
  <label>Origin Address</label>
  <%= form.text_field :origin, class: "form-control" %>
  </div>
  <div class="form-group">
  <label>Destination Address</label>
  <%= form.text_field :destination, class: "form-control" %>
  </div>
  <div class="form-group">
  <label>Number of Passengers</label>
  <%= form.number_field :passengers, class: "form-control" %>
  </div>
  <div class="form-group">
  <label>Phone Number</label>
  <%= form.text_field :phone, class: "form-control" %>
  </div>
  <!-- <div class="form-group"> -->
  <!-- <label>Van</label> -->
  <!-- <br><%#= form.select(:vehicle_id, Ride::VANS, {include_blank: true}) %></br> -->
  <!-- </div> -->
  <button type="submit" class="btn btn-primary btn-block"></a>
  Submit</button>
<% end %>

app/views/rides/edit.html.erb
<h1>Edit Ride</h1>
<%= render "form" %>

app/views/rides/index.haml
!!!
%html
  %head
    %title Click To Call Tutorial
    %link{:rel => "icon", :type => "image/png", :href => "/img/favicon.png"}
    %link{:rel => "stylesheet", :href => "//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"}
    %link{:rel => "stylesheet", :href => "//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css", :type => "text/css"}
    = stylesheet_link_tag 'application', :media => 'all'

  %body
    .container
      %h1 Click To Call
      %p
        Click To Call converts your website's users into engaged customers by creating an easy way for your customers to contact your sales and support teams right on your website.

      %p Here's an example of how it's done!

      %hr

      // C2C contact form
      .row
        .col-md-12
          %form{:id => "contactform", :role => 'form', :action => '#{call_path}', :method => 'POST'}
            .form-group
              %h3 Call Sales
              %p.help-block
                Are you interested in impressing your friends and confounding your enemies? Enter your phone number below, and our team will contact you right away.
            .form-group
              %input.form-control{:type =>'hidden', :name => 'phone', :id => 'phoneNumber', :value => "#{ride.phone}"}
            %button{ :type => 'submit', :class => 'btn btn-default'} Contact Sales

  = javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/rides/index.html.erb
<div class="clearfix">
  <h2 class="pull-xs-left">Rides</h2>
  <%= link_to "New Ride", new_ride_path, class: "btn btn-primary pull-xs-right" %>
</div>

<br>

<table class="table">
  <thead class="thead-default">
    <th>Id</th>
    <th>Van</th>
    <th>Student Id</th>
    <th>Rider Name</th>
    <th>Origin</th>
    <th>Destination</th>
    <th>Passengers</th>
    <th>Phone Number</th>
    <th></th>
  </thead>
  <tbody>
    <% @rides.each do |ride| %>
      <tr>
        <td><%= link_to ride.id, ride %></td>
        <td><%= ride.shift_vehicle_id%></td>
        <td><%= ride.sid%></td>
        <td><%= ride.name%></td>
        <td><%= ride.origin%></td>
        <td><%= ride.destination%></td>
        <td><%= ride.passengers%></td>
        <td><%= ride.phone%></td>
        <td>
          <%= link_to "Edit", edit_ride_path(ride), class: "text-warning" %>
          <%= link_to "Delete", ride_path(ride), class: "text-danger",  method: :delete, 
            data: { confirm: "Are you sure you want to delete this ride?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rides/new.html.erb
<h1 align="center">Request Ride</h1>
<%= render "form" %></div>

app/views/rides/show.html.erb
<div class="clearfix">
  <h2 class="pull-xs-left">Ride #<%= @ride.id %></h2>
  <%= link_to "Edit", edit_ride_path(@ride), class: "btn btn-primary pull-xs-right" %>
</div>

<br>

<div class="row">
  <div class="col-sm-4">
    <dl>
      <dt>Name</dt> 
      <dd><%= @ride.name %></dd>

      <dt>Phone Number</dt> 
      <dd><%= link_to @ride.phone, "tel:#{@ride.phone}" %></dd>

      <dt>Student ID</dt> 
      <dd><%= @ride.sid %></dd>
      <dt>Origin</dt> 
      <dd><%= @ride.origin %></dd>

      <dt>Destination</dt> 
      <dd><%= @ride.destination %></dd>

      <dt>Passengers</dt> 
      <dd><%= @ride.passengers %></dd>

      <dt>Shift Vehicle</dt> 
      <dd><%= @ride.shift_vehicle_id %></dd>
    </dl>
  </div>


  <div class="col-sm-8">
    <div class="google-maps">
      <iframe frameborder="0" style="border:0"
         src="https://www.google.com/maps/embed/v1/directions?origin=<%= @ride.origin %>,Eugene+OR&destination=<%= @ride.destination %>,Eugene+OR&key=<%= ENV["GOOGLE_MAPS_API_KEY"] %>"></iframe> 
    </div>
  </div>
</div>