config/routes.rb
Rails.application.routes.draw do
  resources       :vehicles   do
    resources     :shift_vehicles
    end
  resources       :shifts
  resources       :user_shifts
  resources       :rides
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_scope    :user do get '/users/sign_out' => 'devise/sessions#destroy' end
  devise_for      :users
  # resources       :sessions, only: [:new, :create, :destroy]
  post            'create_shift_vehicles' => "shifts#create_vs"
  root            'static_pages#home'
  post            'create_shift' => 'shifts#create'
  get             'work' => 'shifts#index'
  get             'about' => 'static_pages#about'
  get             'policies' => 'static_pages#policies'
  get             'faq' => 'static_pages#faq'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Designated Driver Shuttle" %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="navbar navbar-full navbar-dark bg-inverse">
      <a class="navbar-brand" href="/">DDS</a>
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item"><%= link_to 'Rides', rides_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to 'Go to Work', create_shift_path, method: :post, class: "nav-link"%></li> <li class="nav-item"><%= link_to 'Vehicles', vehicles_path, class: "nav-link" %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav pull-xs-right">
        <% if user_signed_in? %>
          <li class="nav-item"><%= link_to 'Logout', users_sign_out_path, class: "nav-link" %></li>
        <% else %>
          <li class="nav-item"><%= link_to 'Login', new_user_session_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </nav>

    <div class="container">
      <% unless notice.nil? %>
        <p></p>
        <div class="alert alert-success alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= notice %>
        </div>
      <% end %>
      <p></p>
      <% unless alert.nil? %>
        <div class="alert alert-info alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= alert %>
        </div>
      <% end %>
      <%= yield %>
    </div>

    <!--
    <footer>
      <a href="/rides/new">Request Ride</a>
      <a href="/about">About</a>
      <a href="/policies">Policies</a>
      <a href="/faq">FAQ</a>
    </footer>
    -->
  </body>
</html>